---
#Configuration for scheduler
#########################################################

repo_url: git@github.com:paralect/ansible-node-sample.git
repo_version: master
app_name: demo
server_name: jokes.paralect.com
nginx_servers: ["localhost:9000"]
deploy_dir: "~/{{ app_name }}"
deploy_app_dir: "~/{{ app_name }}/{{ app_name }}-app"


