version: '3'

services:
  web:
   image: apache
   build: .
   container_name: apache_web
   restart: always
   ports:
     - 80
   environment:
     - SERVICE_PORTS=80
   deploy:
     replicas: 20
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - webNet

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - web
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  webNet:
    driver: overlay
