apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
      tier: backend
      track: stable
  replicas: 4
  template:
    metadata:
      labels:
        app: nodeapp
        tier: backend
        track: stable
    spec:
      containers:
        - name: nodeapp
          image: sanurocks5/socialcops:latest
          ports:
            - name: http
              containerPort: 8000